### ISSUE TITLE
Create a start script inside the package.json

### ISSUE THREAD

**Issue by DatBoiLuiskrrt** [DatBoiLuiskrrt/BackendDeliveryBuddy#14]
Inside the `package.json file`, scroll down to where it says `"scripts"` and add
`"start": "node index.js"`. 
***This is a great issue for Hacktoberfest***
#### Please comment that you want to work on this and let me assign you this issue before you start working on it. ####
![image](https://user-images.githubusercontent.com/42678545/195219631-815105b8-7f01-4712-9b59-7a412b92c4ef.png)

**Comment by rio-exe** [comment]
Hey, i wanna work on this :)

**Comment by DatBoiLuiskrrt** [comment]
I have assigned this issue to you :)

**Comment by DatBoiLuiskrrt** [comment]
Issue has been resolved by Agony.
