### ISSUE TITLE
Create a folder and a JS file

### ISSUE THREAD

**Issue by DatBoiLuiskrrt** [DatBoiLuiskrrt/BackendDeliveryBuddy#8]
Inside the api folder create a folder called middleware and inside that folder create a file called middleware.js.
All you have to do is create the files, no need to add any code, that might come in a different issue.

**Comment by DatBoiLuiskrrt** [comment]
![image](https://user-images.githubusercontent.com/42678545/194734233-1425aca3-82d8-4f69-87ed-c08e8f103fcf.png)

**Comment by DatBoiLuiskrrt** [comment]
Create a new branch called Create_A_Folder_And_A_JS_File and push your newly created folder and file to that branch and submit a pull request when done.
This is a great first issue for anyone doing hacktoberfest just ask to be assign to it.

**Comment by VarunGitGood** [comment]
im doing it\

**Comment by DatBoiLuiskrrt** [comment]
I've gone ahead and assigned it to you Varun.

**Comment by VarunGitGood** [comment]
can you review the  pr

**Comment by DatBoiLuiskrrt** [comment]
Pull request merged, issue will be closed. Thank you Varun.
